FROM microsoft/aspnetcore-build:1.0-1.1 as BUILD
COPY . /src
WORKDIR /src
RUN dotnet restore ./DockerDotNetExamples.sln
RUN dotnet test WebApp.Tests/WebApp.Tests.csproj
RUN dotnet publish ./DockerDotNetExamples.sln -c Release -o ./obj/Docker/publish

FROM microsoft/aspnetcore:1.1.2
ARG source
WORKDIR /app
EXPOSE 80
COPY --from=BUILD /src/WebApp/obj/Docker/publish .
ENTRYPOINT ["dotnet", "WebApp.dll"]
